import { Article } from "./types";

export const sampleArticles: Article[] = [
  {
    id: "eth-001",
    title: "EIP-7702: Set EOA account code",
    url: "https://ethresear.ch/t/eip-7702",
    source: "ethresear.ch",
    sourceUrl: "https://ethresear.ch",
    category: "blockchain",
    subcategory: "ethereum",
    date: "2025-04-01",
    excerpt: "A new proposal allowing EOAs to set their account code for a single transaction, enabling smart account features without migration.",
    author: "Vitalik Buterin",
  },
  {
    id: "eth-002",
    title: "The Endgame for Ethereum Execution",
    url: "https://vitalik.eth.limo/general/2025/03/execution.html",
    source: "Vitalik Buterin",
    sourceUrl: "https://vitalik.eth.limo",
    category: "blockchain",
    subcategory: "consensus-researchers",
    date: "2025-03-28",
    excerpt: "Exploring the long-term vision for Ethereum's execution layer, including statelessness, SNARKification, and the role of L2s.",
    author: "Vitalik Buterin",
    summary: "Vitalik, Ethereum'un execution katmanının geleceğini tartışıyor. Stateless client'lar, SNARK-based verification ve L2'lerin rollup-centric roadmap'teki rolü ana temalar.",
  },
  {
    id: "sol-001",
    title: "Solana's Turbine Block Propagation: A Deep Dive",
    url: "https://solana.com/news/turbine-deep-dive",
    source: "Solana News",
    sourceUrl: "https://solana.com/news",
    category: "blockchain",
    subcategory: "solana",
    date: "2025-03-25",
    excerpt: "An in-depth analysis of Solana's Turbine protocol and recent improvements to block propagation efficiency.",
  },
  {
    id: "monad-001",
    title: "Parallel Execution in Monad: Architecture Overview",
    url: "https://blog.monad.xyz/parallel-execution",
    source: "Monad Blog",
    sourceUrl: "https://blog.monad.xyz",
    category: "blockchain",
    subcategory: "monad",
    date: "2025-03-30",
    excerpt: "How Monad achieves parallel execution while maintaining Ethereum compatibility through optimistic concurrency control.",
    summary: "Monad'ın parallel execution modeli optimistic concurrency control kullanıyor. EVM uyumluluğunu korurken 10,000+ TPS hedefleniyor.",
  },
  {
    id: "eigen-001",
    title: "Restaking Economics: Shared Security at Scale",
    url: "https://blog.eigencloud.xyz/restaking-economics",
    source: "EigenCloud Blog",
    sourceUrl: "https://blog.eigencloud.xyz",
    category: "blockchain",
    subcategory: "eigenlayer",
    date: "2025-03-20",
    excerpt: "A formal analysis of the economic security properties of restaking protocols and their implications for AVS design.",
  },
  {
    id: "ai-001",
    title: "Scaling Reasoning in Large Language Models",
    url: "https://openai.com/blog/scaling-reasoning",
    source: "OpenAI Blog",
    sourceUrl: "https://openai.com/blog",
    category: "ai-ml",
    subcategory: "ai-labs",
    date: "2025-04-02",
    excerpt: "New research on chain-of-thought reasoning capabilities and how compute-optimal training improves multi-step problem solving.",
    author: "OpenAI Research",
  },
  {
    id: "ai-002",
    title: "AlphaGeometry 2: Solving Olympiad Problems",
    url: "https://deepmind.google/blog/alphageometry-2",
    source: "DeepMind Blog",
    sourceUrl: "https://deepmind.google/blog",
    category: "ai-ml",
    subcategory: "ai-labs",
    date: "2025-03-22",
    excerpt: "DeepMind's latest model achieves gold-medal level performance on International Mathematical Olympiad geometry problems.",
    summary: "AlphaGeometry 2, IMO geometri problemlerinde altın madalya seviyesine ulaştı. Neuro-symbolic yaklaşımla pure neural baseline'ı geçiyor.",
  },
  {
    id: "ai-003",
    title: "A Survey of Mixture-of-Experts Architectures",
    url: "https://lilianweng.github.io/posts/2025-03-moe/",
    source: "Lilian Weng",
    sourceUrl: "https://lilianweng.github.io",
    category: "ai-ml",
    subcategory: "ai-researchers",
    date: "2025-03-15",
    excerpt: "Comprehensive overview of MoE architectures, from Switch Transformers to recent advances in expert routing and load balancing.",
    author: "Lilian Weng",
  },
  {
    id: "gt-001",
    title: "Mechanism Design for AI Agents",
    url: "https://terrytao.wordpress.com/2025/03/mechanism-design-ai",
    source: "Terence Tao",
    sourceUrl: "https://terrytao.wordpress.com",
    category: "game-theory",
    subcategory: "math-decision",
    date: "2025-03-18",
    excerpt: "Mathematical foundations for designing incentive-compatible mechanisms when participants include both humans and AI agents.",
    author: "Terence Tao",
  },
  {
    id: "gt-002",
    title: "The Alignment Tax: A Game-Theoretic Analysis",
    url: "https://www.lesswrong.com/posts/alignment-tax-game-theory",
    source: "LessWrong",
    sourceUrl: "https://www.lesswrong.com",
    category: "game-theory",
    subcategory: "math-decision",
    date: "2025-03-12",
    excerpt: "Formalizing the cost of alignment as a game between capability-maximizing and safety-preserving objectives.",
  },
  {
    id: "qt-001",
    title: "Post-Quantum Signatures: Lattice-Based Approaches",
    url: "https://blog.cryptographyengineering.com/2025/03/pq-lattice",
    source: "Matthew Green",
    sourceUrl: "https://blog.cryptographyengineering.com",
    category: "quantum-crypto",
    subcategory: "quantum-researchers",
    date: "2025-03-10",
    excerpt: "A practical guide to lattice-based signature schemes and their readiness for real-world deployment in blockchain systems.",
    author: "Matthew Green",
  },
  {
    id: "arxiv-001",
    title: "Optimal MEV Extraction Under Incomplete Information",
    url: "https://arxiv.org/abs/2503.12345",
    source: "arXiv: Game Theory",
    sourceUrl: "https://arxiv.org/list/cs.GT/recent",
    category: "academic",
    subcategory: "arxiv",
    date: "2025-03-29",
    excerpt: "We study the problem of maximal extractable value in decentralized exchanges under Bayesian game-theoretic frameworks.",
  },
  {
    id: "mev-001",
    title: "SUAVE: The Future of MEV Supply Chain",
    url: "https://writings.flashbots.net/suave-future",
    source: "Flashbots Research",
    sourceUrl: "https://writings.flashbots.net",
    category: "blockchain",
    subcategory: "defi-mev",
    date: "2025-03-26",
    excerpt: "An updated vision for SUAVE and how it aims to decentralize the MEV supply chain across multiple domains.",
    summary: "Flashbots'un SUAVE vizyonu: MEV supply chain'ini birden fazla domain'de merkeziyetsizleştirmek. Cross-chain MEV ve builder decentralization ana odak.",
  },
  {
    id: "starknet-001",
    title: "Cairo 2.0: Provable Computation Made Practical",
    url: "https://community.starknet.io/t/cairo-2-provable-computation",
    source: "StarkNet Community",
    sourceUrl: "https://community.starknet.io",
    category: "blockchain",
    subcategory: "starknet",
    date: "2025-03-23",
    excerpt: "Overview of Cairo 2.0's Rust-like syntax and how it makes writing provable programs accessible to a wider developer audience.",
  },
  {
    id: "cosmos-001",
    title: "IBC v2: Cross-Chain Communication Reimagined",
    url: "https://medium.com/the-interchain-foundation/ibc-v2",
    source: "Cosmos Blog",
    sourceUrl: "https://medium.com/the-interchain-foundation",
    category: "blockchain",
    subcategory: "cosmos",
    date: "2025-03-19",
    excerpt: "The next generation of Inter-Blockchain Communication protocol with improved latency, security, and multi-hop routing.",
  },
  {
    id: "quanta-001",
    title: "Mathematicians Discover New Class of Fair Division Algorithms",
    url: "https://www.quantamagazine.org/fair-division-algorithms",
    source: "Quanta Magazine",
    sourceUrl: "https://www.quantamagazine.org",
    category: "game-theory",
    subcategory: "math-decision",
    date: "2025-03-08",
    excerpt: "A breakthrough in computational fair division that achieves envy-freeness with bounded number of cuts.",
  },
];
